In [237]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [238]:
dataset = pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [239]:
print(x)

[['Ferrari' 50.0 36000.0]
 ['RedBull' nan 41000.0]
 ['AstonMartin' 30.0 60000.0]
 ['RedBull' 38.0 61000.0]
 ['Ferrari' 30.0 nan]
 ['RedBull' 35.0 58000.0]
 ['AstonMartin' 21.0 52000.0]
 ['RedBull' 48.0 79000.0]
 ['Ferrari' 50.0 83000.0]
 ['AstonMartin' 37.0 67000.0]]


In [240]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [241]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [242]:
print(x)

[['Ferrari' 50.0 36000.0]
 ['RedBull' 37.666666666666664 41000.0]
 ['AstonMartin' 30.0 60000.0]
 ['RedBull' 38.0 61000.0]
 ['Ferrari' 30.0 59666.666666666664]
 ['RedBull' 35.0 58000.0]
 ['AstonMartin' 21.0 52000.0]
 ['RedBull' 48.0 79000.0]
 ['Ferrari' 50.0 83000.0]
 ['AstonMartin' 37.0 67000.0]]


In [243]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
     

In [244]:
print(x)


[[0.0 1.0 0.0 50.0 36000.0]
 [0.0 0.0 1.0 37.666666666666664 41000.0]
 [1.0 0.0 0.0 30.0 60000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 30.0 59666.666666666664]
 [0.0 0.0 1.0 35.0 58000.0]
 [1.0 0.0 0.0 21.0 52000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [245]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [246]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [247]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [248]:
print(x_train)

[[1.0 0.0 0.0 21.0 52000.0]
 [0.0 1.0 0.0 30.0 59666.666666666664]
 [0.0 1.0 0.0 50.0 36000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 37.666666666666664 41000.0]
 [0.0 0.0 1.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 35.0 58000.0]]


In [249]:
print(x_test)

[[1.0 0.0 0.0 30.0 60000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [250]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [251]:
print(y_test)

[0 1]


In [252]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [253]:
print(x_train)

[[1.0 0.0 0.0 -1.833686004594795 -0.4372820977874461]
 [0.0 1.0 0.0 -0.901742058730146 0.062468871112492504]
 [0.0 1.0 0.0 1.1692444876357406 -1.4802406415786227]
 [0.0 0.0 1.0 -0.07334744018379133 0.1493820830950907]
 [0.0 0.0 1.0 -0.10786388262322302 -1.15431609664388]
 [0.0 0.0 1.0 0.962145832999152 1.3227104448601643]
 [0.0 1.0 0.0 1.1692444876357406 1.5834500808079586]
 [0.0 0.0 1.0 -0.3839954221386743 -0.0461726438657549]]


In [254]:
print(x_test)

[[1.0 0.0 0.0 -0.901742058730146 0.08419717410814218]
 [1.0 0.0 0.0 -0.17689676750208566 0.5404915370167819]]
